// Generated by CoffeeScript 1.10.0
(function() {
  var enableClick, init;

  enableClick = function() {
    document.getElementById('helloButton').onclick = function() {
      var name;
      name = document.getElementById('nameInput').value;
      gapi.client.myApi.sayHi({
        'name': name
      }).execute(function(response) {
        var outputAlertDiv;
        outputAlertDiv = document.getElementById('outputAlert');
        outputAlertDiv.style.visibility = 'visible';
        if (!response.error) {
          outputAlertDiv.className = 'alert alert-success';
          outputAlertDiv.innerHTML = '<h2>' + response.result.data + '</h2>';
        } else if (response.error) {
          outputAlertDiv.className = 'alert alert-danger';
          outputAlertDiv.innerHTML = '<b>Error Code: </b>' + response.error.code + ' [' + response.error.message + ']';
        }
      });
      return false;
    };
  };

  init = function() {
    var apiName, apiRoot, apiVersion, callback;
    apiName = 'myApi';
    apiVersion = 'v1';
    apiRoot = 'https://' + window.location.host + '/_ah/api';
    if (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1' || window.location.port !== '' && window.location.port > 1023) {
      apiRoot = 'http://' + window.location.host + '/_ah/api';
    }
    callback = function() {
      enableClick();
    };
    gapi.client.load(apiName, apiVersion, callback, apiRoot);
  };

}).call(this);
